force-app/main/default/objects/Result__c/Result__c.object-meta.xml
<CustomObject>
    <label>Result</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Result Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Result__c/fields/Collected__c.field-meta.xml
<CustomField>
    <fullName>Collected__c</fullName>
    <defaultValue>now()</defaultValue>
    <label>Collected</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Result__c/fields/Cycle__c.field-meta.xml
<CustomField>
    <fullName>Cycle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cycle</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Result</relationshipLabel>
    <relationshipName>Result</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Result__c/fields/E2__c.field-meta.xml
<CustomField>
    <fullName>E2__c</fullName>
    <label>E2</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Result__c/fields/HCG__c.field-meta.xml
<CustomField>
    <fullName>HCG__c</fullName>
    <label>HCG</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Result__c/fields/LH__c.field-meta.xml
<CustomField>
    <fullName>LH__c</fullName>
    <description>LH Blood Results Field</description>
    <label>LH</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Result__c/fields/P4__c.field-meta.xml
<CustomField>
    <fullName>P4__c</fullName>
    <label>P4</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Result__c/fields/Result_Type__c.field-meta.xml
<CustomField>
    <fullName>Result_Type__c</fullName>
    <label>Result Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Blood Test Result</fullName>
                <default>true</default>
                <label>Blood Test Result</label>
            </value>
            <value>
                <fullName>Pregnancy Test Result</fullName>
            </value>
            <value>
                <fullName>Where in Cycle Blood</fullName>
            </value>
            <value>
                <fullName>Infectious Screens</fullName>
            </value>
            <value>
                <fullName>Scan</fullName>
            </value>
            <value>
                <fullName>Pregnancy Scan</fullName>
            </value>
            <value>
                <fullName>Record Ovulation</fullName>
            </value>
            <value>
                <fullName>Pregnancy Histopathology</fullName>
            </value>
            <value>
                <fullName>Antral Follicle Count</fullName>
            </value>
            <value>
                <fullName>Anti Mullerian Hormone</fullName>
            </value>
            <value>
                <fullName>PGT Result</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ResultController.cls
public with sharing class ResultController {
    @AuraEnabled(cacheable=true)
    public static List<Result__c> getResults(Id caseId) {
        return [
            SELECT Id, E2__c, LH__c, P4__c, HCG__c
            FROM Result__c
            WHERE Cycle__c = :caseId AND Result_Type__c IN ('Blood Test Result', 'Pregnancy Test Result', 'Where in Cycle Blood')
            ORDER BY Collected__c DESC
            LIMIT 2
        ];
    }
}